# 1. THE LAYOUT
format = """
$username\
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

add_newline = true

# 2. THE ARROW (Bottom Line)
[character]
success_symbol = "[>](bold #0077b6)"
error_symbol = "[>](bold red)"

# 3. USERNAME (Cyan)
[username]
show_always = true
style_user = "bold #48cae4"
style_root = "bold red"
format = '[$user]($style) '

# 4. DIRECTORY (Deep Blue)
[directory]
style = "bold #023e8a"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = ".../"

# 5. GIT (Medium Blue & Red for dirty status)
[git_branch]
style = "bold #0077b6"
format = '\[git:[$branch]($style)\] '

[git_status]
style = "bold #ef233c"
format = '[$all_status$ahead_behind]($style) '