name: ROS 2 Workspace Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-workspace:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zcmarinerobotics/zc-marine-robotics-ws:latest
      options: --user root
    
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Build Workspace
        run: |
          source /opt/ros/lyrical/setup.bash
          colcon build --symlink-install --event-handlers console_direct+